from zoneinfo import ZoneInfo

# Huso horario de Argentina
ARGENTINA_TZ = ZoneInfo("America/Buenos_Aires")

# Horario del merval
MARKET_OPEN_HOUR = 10
MARKET_OPEN_MINUTE = 30
MARKET_CLOSE_HOUR = 17
MARKET_CLOSE_MINUTE = 00

APERTURA_MERVAL_HORA = 10
APERTURA_MERVAL_MINUTOS = 30
CIERRE_MERVAL_HORA = 17
CIERRE_MERVAL_MINUTOS = 00
